"""
llm_client.py — Common interface, data models, and factory for LLM providers.

This module provides the abstract base class `BaseLLMProvider`, standardised
data models for responses and health status, custom exceptions, and a factory
function `get_llm_provider()` to instantiate configured providers without
leaking implementation details or secret API keys.
"""

from __future__ import annotations

import json
import logging
import re
from abc import ABC, abstractmethod
from typing import Any, Dict, Generic, Optional, Type, TypeVar

from pydantic import BaseModel, Field

from config import LLMProvider, settings

logger = logging.getLogger(__name__)

T = TypeVar("T", bound=BaseModel)

# ─────────────────────────────────────────────────────────────────────────────
# Custom Exceptions
# ─────────────────────────────────────────────────────────────────────────────

class LLMError(Exception):
    """Base exception for all LLM provider errors."""
    pass


class LLMAuthenticationError(LLMError):
    """Raised when API credentials or keys are missing or invalid."""
    pass


class LLMConnectionError(LLMError):
    """Raised when the LLM endpoint cannot be reached (offline/network failure)."""
    pass


class LLMResponseError(LLMError):
    """Raised when the provider returns an unexpected error or bad payload."""
    pass


class LLMParsingError(LLMError):
    """Raised when structured output generation fails to match the required schema."""
    pass


# ─────────────────────────────────────────────────────────────────────────────
# Standardised Data Models
# ─────────────────────────────────────────────────────────────────────────────

class LLMUsage(BaseModel):
    """Token consumption statistics for an LLM interaction."""
    prompt_tokens: int = Field(default=0, description="Tokens in the input prompt.")
    completion_tokens: int = Field(default=0, description="Tokens generated by the model.")
    total_tokens: int = Field(default=0, description="Total tokens consumed.")


class LLMResponse(BaseModel):
    """Standardised result returned by any LLM provider generate() call."""
    content: str = Field(..., description="Raw text generated by the LLM.")
    model: str = Field(..., description="Model identifier used for generation.")
    provider: str = Field(..., description="Provider backend ('gemini' or 'ollama').")
    usage: LLMUsage = Field(default_factory=LLMUsage, description="Token usage statistics.")
    latency_ms: float = Field(default=0.0, description="Response generation time in milliseconds.")
    status: str = Field(default="success", description="Status code ('success' or 'error').")
    error_message: Optional[str] = Field(default=None, description="Descriptive error message if failed.")
    raw_response: Optional[Dict[str, Any]] = Field(default=None, description="Raw provider metadata.")


class LLMStructuredResponse(BaseModel, Generic[T]):
    """Standardised result for schema-constrained structured output generation."""
    parsed_data: Optional[Any] = Field(default=None, description="Validated Pydantic model instance.")
    raw_text: str = Field(default="", description="Original raw text response from the model.")
    is_valid: bool = Field(default=False, description="Whether parsing and validation succeeded.")
    error_message: Optional[str] = Field(default=None, description="Parsing or validation error details.")
    response_metadata: Optional[LLMResponse] = Field(default=None, description="Underlying LLMResponse metadata.")


class LLMHealthStatus(BaseModel):
    """Health status check result for an LLM provider backend."""
    is_healthy: bool = Field(..., description="True if provider is online and ready for requests.")
    provider: str = Field(..., description="Provider backend ('gemini' or 'ollama').")
    model: str = Field(..., description="Model identifier.")
    status_message: str = Field(..., description="Human-readable status or diagnostic error message.")
    latency_ms: Optional[float] = Field(default=None, description="Latency of health check ping in ms.")


# ─────────────────────────────────────────────────────────────────────────────
# Abstract Base Class
# ─────────────────────────────────────────────────────────────────────────────

class BaseLLMProvider(ABC):
    """
    Abstract interface for all LLM providers (Gemini, Ollama, etc.).

    Decouples application logic from specific LLM SDK implementations.
    """

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Return the unique provider name (e.g. 'gemini' or 'ollama')."""
        pass

    @property
    @abstractmethod
    def model_name(self) -> str:
        """Return the active model name (e.g. 'gemini-2.0-flash' or 'llama3.2')."""
        pass

    @abstractmethod
    def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        temperature: float = 0.2,
        max_tokens: Optional[int] = None,
    ) -> LLMResponse:
        """
        Generate text completion from prompt.

        Args:
            prompt: User input or prompt string.
            system_prompt: Optional system instruction guiding model behavior.
            temperature: Sampling temperature (0.0 to 1.0).
            max_tokens: Maximum tokens allowed in completion.

        Returns:
            LLMResponse object with generated content and metadata.
        """
        pass

    @abstractmethod
    def generate_structured(
        self,
        prompt: str,
        schema: Type[T],
        system_prompt: Optional[str] = None,
        temperature: float = 0.1,
    ) -> LLMStructuredResponse[T]:
        """
        Generate structured output adhering to a Pydantic schema.

        Args:
            prompt: User input or prompt string.
            schema: Pydantic model class to validate the response against.
            system_prompt: Optional system prompt.
            temperature: Sampling temperature.

        Returns:
            LLMStructuredResponse wrapping the validated Pydantic model instance.
        """
        pass

    @abstractmethod
    def health_check(self) -> LLMHealthStatus:
        """
        Check if the LLM provider backend is online, credentials valid, and ready.

        Returns:
            LLMHealthStatus containing status boolean and diagnostic message.
        """
        pass

    @staticmethod
    def mask_secret(secret: Optional[str]) -> str:
        """
        Safely mask secret keys to prevent accidental logging or exposure in UI.

        Examples:
            'AQ.Ab8RN6JpVSadhiQQ' -> 'AQ.A...hiQQ'
            None -> '<UNSET>'
        """
        if not secret:
            return "<UNSET>"
        if len(secret) <= 8:
            return "****"
        return f"{secret[:4]}...{secret[-4:]}"

    @staticmethod
    def clean_json_text(text: str) -> str:
        """
        Extract clean JSON text from LLM response, handling markdown codeblocks.

        Removes wrapping ```json ... ``` or ``` ... ``` markers while preserving
        code fences embedded inside JSON string values.
        """
        if not text:
            return ""
        text = text.strip()

        # 1. Direct validation: if already valid JSON, return immediately
        try:
            json.loads(text)
            return text
        except (ValueError, TypeError):
            pass

        # 2. Check if text is enclosed in outermost markdown code blocks: ```json ... ``` or ``` ... ```
        if text.startswith("```") and text.endswith("```"):
            first_newline = text.find("\n")
            if first_newline != -1:
                candidate = text[first_newline + 1 : -3].strip()
                try:
                    json.loads(candidate)
                    return candidate
                except (ValueError, TypeError):
                    text = candidate

        # 3. Find outermost JSON object {...} or array [...]
        first_brace = text.find("{")
        first_bracket = text.find("[")

        if first_brace != -1 or first_bracket != -1:
            if first_brace != -1 and (first_bracket == -1 or first_brace < first_bracket):
                start = first_brace
                end = text.rfind("}")
            else:
                start = first_bracket
                end = text.rfind("]")

            if end != -1 and end > start:
                candidate = text[start : end + 1].strip()
                return candidate

        return text


# ─────────────────────────────────────────────────────────────────────────────
# Factory Function
# ─────────────────────────────────────────────────────────────────────────────

def get_llm_provider(provider_name: Optional[str] = None) -> BaseLLMProvider:
    """
    Factory to obtain an instance of the configured LLM provider.

    Args:
        provider_name: Name of provider ('gemini' or 'ollama').
                       If None, reads from global application `settings.llm_provider`.

    Returns:
        Instance of BaseLLMProvider implementation.

    Raises:
        ValueError: If specified provider name is invalid/unsupported.
    """
    target_provider = (provider_name or settings.llm_provider).lower()
    if isinstance(target_provider, LLMProvider):
        target_provider = target_provider.value

    if target_provider == LLMProvider.GEMINI.value:
        from llm.gemini_provider import GeminiProvider
        return GeminiProvider()
    elif target_provider == LLMProvider.OLLAMA.value:
        from llm.ollama_provider import OllamaProvider
        return OllamaProvider()
    else:
        raise ValueError(
            f"Unsupported LLM provider: '{target_provider}'. "
            f"Supported providers are: {[p.value for p in LLMProvider]}"
        )
