"""
ui/final_report_page.py — Browse and view final reports from completed reviews.

Reads completed review threads from the SQLite checkpointer and displays the
Markdown reports generated by the LangGraph pipeline.
"""

from __future__ import annotations

import logging
from typing import Any, Dict

import streamlit as st

from graph.workflow import build_review_graph
from storage.checkpoint_db import get_default_db_path, get_sqlite_checkpointer, list_checkpoint_threads

logger = logging.getLogger(__name__)


def render() -> None:
    st.title("📄 Final Reports")
    st.markdown(
        """
        Browse and view historical Code Review reports generated by the LangGraph pipeline.
        Reports are persisted across sessions in the local SQLite checkpointer database.
        """
    )

    db_path = get_default_db_path()
    saver = get_sqlite_checkpointer(db_path)
    
    # We compile the graph just to get access to `app.get_state()` 
    # (or we could use the saver directly, but using the app is cleaner)
    app = build_review_graph(checkpointer=saver)

    # ── Thread Selection ──────────────────────────────────────────────────────
    threads = list_checkpoint_threads(db_path)
    thread_ids = [t["thread_id"] for t in threads]

    col_select, col_refresh = st.columns([4, 1])
    with col_select:
        if thread_ids:
            selected_thread = st.selectbox(
                "Select a Review Thread to View:",
                options=thread_ids,
                index=0,
                help="Historical runs are uniquely identified by their thread ID.",
            )
        else:
            selected_thread = None
            st.info("No review threads found in the checkpoint database.")
            
    with col_refresh:
        st.markdown("<div style='margin-top:1.8rem;'></div>", unsafe_allow_html=True)
        if st.button("🔄 Refresh", use_container_width=True):
            st.rerun()

    if not selected_thread:
        return

    # ── Fetch Thread State from Checkpointer ──────────────────────────────────
    config = {"configurable": {"thread_id": selected_thread}}
    try:
        snapshot = app.get_state(config)
    except Exception as exc:
        st.error(f"Failed to load checkpoint state for thread `{selected_thread}`: {exc}")
        return

    values: Dict[str, Any] = snapshot.values if snapshot else {}
    report = values.get("final_report", "")

    st.divider()

    if not report:
        st.warning(f"Thread `{selected_thread}` does not contain a final report. It may still be running or paused.")
        
        next_nodes = snapshot.next if snapshot else ()
        if next_nodes:
            st.info(f"Thread is currently at nodes: {', '.join(next_nodes)}")
        return

    st.success(f"Loaded report for thread: `{selected_thread}`")
    
    with st.container(border=True):
        st.markdown(report)
